@baseUrl = http://127.0.0.1:3333/api
@contentType = application/json

### lists place
GET  {{baseUrl}}/places HTTP/1.1

### create place
POST {{baseUrl}}/place/create HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "aeon",
    "description": "store tangerang",
    "location": {
        "lat": "-6.3047146",
        "long": "106.6439975"
    }
}

### update place
PATCH {{baseUrl}}/place/3 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "smb",
    "description": "bekasi"
}