@baseUrl = https://i0rtv.sse.codesandbox.io/api
@contentType = application/json
@authorization = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTU3MjU0NjUwNH0.a2spZoT_N5FGv8SgkLAljV0sOgzi3RLykuZ6i5NPb6g

###login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "yuni@outlook.com",
    "password": "123456"
}


### profile
GET {{baseUrl}}/user HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{authorization}}

### users
GET {{baseUrl}}/users HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{authorization}}

### create user
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: {{contentType}}
# Authorization: {{authorization}}

{
    "email": "yuni@outlook.com",
    "password": "123456"
}

### create user profile
POST  {{baseUrl}}/profile/create
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
    "fullname": "yuniestri imanti",
    "address": "jakarta",
    "birthdate": "23-10-1991"
}

### update user
PATCH {{baseUrl}}/profile/2
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
    "fullname": "wawan sumardi",
    "gender": 2,
    "education": "s3"
}

### delete user
DELETE {{baseUrl}}/user/6
Content-Type: {{contentType}}
Authorization: {{authorization}}
